#!/usr/bin/env bash

# A quick and dirty script to a full disk setup this
# script uses gdisk to create a GPT disk table and
# create all basic partitions
#

# Create the GPT Partition table

echo -e "
o
y
w
y
" | gdisk "${1}"

# Create the EFI Partition

echo -e "
n


+512M
EF00
w
y
" | gdisk "${1}"


# Create the EXT4 Partition

echo -e "
n




w
y
" | gdisk "${1}"

echo y | mkfs.fat  -F32 "${1}1"
echo y | mkfs.ext4 "${1}2"
